name: Unpack Xamarin Blob
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Aggiornato a v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5 # Aggiornato a v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install lz4 xxhash setuptools
          git clone https://github.com/jakev/pyXamStore.git pyxamstore

      - name: Run Extraction
        run: python estrai.py

      - name: Upload DLLs
        uses: actions/upload-artifact@v4 # <--- QUI C'ERA L'ERRORE, ORA È V4
        with:
          name: OpenFiber-DLLs
          path: DLL_ESTRATTE/
